# Generated by Django 6.0.2 on 2026-02-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('component', 'Component'), ('battery', 'Battery/Power Source')], default='component', max_length=20),
        ),
        migrations.AddField(
            model_name='block',
            name='current',
            field=models.FloatField(default=0.0, help_text='Current consumption in A (for components) or max supply current (for batteries)'),
        ),
        migrations.AddField(
            model_name='block',
            name='voltage',
            field=models.FloatField(default=0.0, help_text='Operating voltage in V (for components) or output voltage (for batteries)'),
        ),
    ]
