# Generated by Django 6.0.2 on 2026-03-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_settings_remove_user_cost_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional block image (will be displayed as a square)', null=True, upload_to='blocks/'),
        ),
    ]
