# Generated by Django 6.0.2 on 2026-03-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_block_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='voltage',
        ),
        migrations.AddField(
            model_name='block',
            name='voltage_max',
            field=models.FloatField(default=0.0, help_text='Maximum voltage in V (for components) or same as min for fixed voltage'),
        ),
        migrations.AddField(
            model_name='block',
            name='voltage_min',
            field=models.FloatField(default=0.0, help_text='Minimum voltage in V (for components) or output voltage (for batteries)'),
        ),
    ]
